"""add document storage fields

Revision ID: ef8ef229d335
Revises: 1662a9d97b4c
Create Date: 2026-08-03 22:14:38.832017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8ef229d335'
down_revision: Union[str, Sequence[str], None] = '1662a9d97b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_key', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('document_url', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('mime_type', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_unique_constraint(None, 'documents', ['document_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_column('documents', 'content_hash')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'document_url')
    op.drop_column('documents', 'document_key')
    # ### end Alembic commands ###
